config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  scope :errors do
    get 'unauthorized', to: 'errors#unauthorized'
  end

  scope :auth do
    get 'not_logged', to: 'auth#not_logged'
    post 'login', to: 'auth#login'
    post 'logout', to: 'auth#logout'


  end

  resources :users, only: []  do
    resources :tasks, only: :index
  end

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        resources :tasks
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  has_many :task_tags, dependent: :destroy
  has_many :tasks, through: :task_tags

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user,
                                 message: "Ya tienes una etiqueta con ese nombre" }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags, before_add: :validate_tags_number

  validates :title, :priority, :status, presence: true
  validates :status, inclusion: { in: %w(done to_do),
                                message: "%{value} no es un estado válido" }

  private

  def validate_tags_number(tag)
    if tag_ids.count > 3
      errors.add(:tags, "No puedes tener más de 3 etiquetas asociadas a la misma tarea")
      raise ActiveRecord::Rollback
    end
  end
end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag

  validates :tag, uniqueness: { scope: :task,
                                 message: "Una tarea no puede tener más de una etiqueta con el mismo nombre" }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  after_create :generate_api_key

  def generate_api_key
    self.api_key = SecureRandom.hex
    self.save
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate

  rescue_from ActiveRecord::RecordNotFound do |error|
    render json: { error: "record not found" }, status: :not_found
  end

  private

  def authenticate
    authenticate_with_token || unauthorized
  end

  def authenticate_with_token
    authenticate_with_http_token do |token|
      @user ||= User.find_by(api_key: token)
    end
  end

  def unauthorized
    head :unauthorized
  end

  def serialize(records)
    records.as_json(except: [:created_at, :updated_at, :user_id],
                 include: {tags: {except: [:created_at, :updated_at, :user_id]}})
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::BaseController
  before_action :set_task, only: [:show, :update, :destroy]

  def index
    tasks = @user.tasks
    render json: serialize(tasks)
  end

  def show
    render json: serialize(@task)
  end

  def create
    task = @user.tasks.build(task_params)
    if task.save
      render json: serialize(task)
    else
      render json: task.errors
    end
  end

  def update
    if @task.update(task_params)
      render json: serialize(@task)
    else
      render json: task.errors
    end
  end

  def destroy
    @task.destroy

    head :no_content
  end

  private

  def set_task
    @task = @user.tasks.find(params[:id])
  end

  def task_params
    params.permit(:title, :description, :status, :priority, :deadline)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CurrentUser
  include AuthenticateUser
end

app/controllers/auth_controller.rb
class AuthController < ActionController::Base
  layout "application"

  def not_logged
  end

  def login
    @user = User.find_or_initialize_by(email: params[:email])
    if @user.save
      cookies.signed.permanent[:user_email] = params[:email]
      redirect_to root_path
    else
      render :not_logged
    end
  end

  def logout
    cookies.delete :user_email
    redirect_to not_logged_path
  end
end

app/controllers/concerns/authenticate_user.rb
module AuthenticateUser
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user!
  end

  private

  def authenticate_user!
    redirect_to not_logged_path unless @current_user
  end
end

app/controllers/concerns/current_user.rb
module CurrentUser
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
  end

  private

  def set_current_user
    @current_user ||= User.find_by_email(cookies.signed.permanent[:user_email])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def unauthorized
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user

  def index
    redirect_to errors_unauthorized_path unless policy.allowed?

    tasks = Tasks::FilterQuery.new(user_id: @current_user.id,
                                   from_date: Date.today,
                                   to_date: Date.today + 1.week,
                                   status: "to_do",
                                   tag_id: params[:tag_id])
                              .call

    @tasks = tasks.includes(:tags).order(:priority, :deadline)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    @user = @current_user
  end

  def policy
    TaskPolicy.new(@current_user, @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guud Todoist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield :sidebar %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_empty.html.erb
<div class="empty">
  <%= image_tag "#{img}.svg", class: "empty__img" %>
  <span class="empty__title"><%= title %></span>
</div>

app/views/tasks/_tag_list.html.erb
<ul class="tags__list">
  <li class="tags__item"><%= link_to "Todas las tareas", user_tasks_path(@current_user.id), class: "btn" %></li>
  <% tags.each do |tag| %>
    <li class="tags__item"><%= link_to "#{tag.name}", user_tasks_path(user_id: @current_user.id, tag_id: tag.id), class: "btn" %></li>
  <% end %>
</ul>

app/views/tasks/_task.html.erb
<div class="card">
  <div class="card__title"><%= task.title %></div>
  <div>
    <% task.tags.each do |tag| %>
      <span class="tag"><%= link_to "#{tag.name}", user_tasks_path(user_id: @current_user.id, tag_id: tag.id), class: "btn" %></span>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<span class="api_key">API KEY: <%= @current_user.api_key %></span>
<%= button_to "Salir", logout_path, class: "logout btn danger rounded" %>

<%= content_for :sidebar do %>
  <aside class="tags">
    <%= render partial: 'tasks/tag_list', locals: {tags: @current_user.tags } %>
  </aside>
<% end %>

<section class="tasks">
  <%= render partial: "tasks/task", collection: @tasks %>
</section>

<%= render partial: "shared/empty", locals: { img: "empty_tasks", title: "No tienes tareas pendientes" } if @tasks.empty? %>